# Generated by Django 3.0.5 on 2020-04-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteengine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
