# Generated by Django 3.0.5 on 2020-04-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteengine', '0002_auto_20200415_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='color',
            field=models.CharField(default='primary', max_length=10),
            preserve_default=False,
        ),
    ]
