# Generated by Django 3.0.5 on 2020-04-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteengine', '0004_auto_20200416_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaperimg',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
