# Generated by Django 3.0.5 on 2020-04-17 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteengine', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteengine.WallpaperImg')),
            ],
        ),
    ]
